name: Build GoPro‑MAX FFmpeg – Windows

on:
  workflow_dispatch:          # press “Run workflow” to refresh binaries

jobs:
  win-x64:
    runs-on: windows-latest
    name: Windows‑x64 build

    steps:
    # 1 – workspace (repo can be empty)
    - uses: actions/checkout@v4

    # 2 – MSYS2 toolchain + OpenCL
    - name: Install MSYS2 toolchain
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
          git
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-yasm
          mingw-w64-x86_64-nasm
          mingw-w64-x86_64-opencl-headers
          mingw-w64-x86_64-opencl-icd

    # 3 – build static x264
    - name: Build static x264
      shell: msys2 {0}
      run: |
        set -e
        git clone --depth 1 https://code.videolan.org/videolan/x264.git
        cd x264
        ./configure --enable-static --disable-opencl --prefix=/mingw64
        make -j"$(nproc)"
        make install
        cd ..

    # 4 – build FFmpeg fork (OpenCL + x264)
    - name: Build FFmpeg (GoPro fork)
      shell: msys2 {0}
      run: |
        set -e
        git clone --depth 1 https://github.com/gmat/goproMax-ffmpeg-v5.git
        cd goproMax-ffmpeg-v5
        ./configure \
          --cc=gcc \
          --target-os=mingw32 --arch=x86_64 \
          --enable-cross-compile \
          --enable-gpl --enable-nonfree \
          --enable-opencl \
          --enable-libx264 \
          --disable-asm \
          --disable-doc
        make -j"$(nproc)"

        # copy EXEs
        cp ffmpeg.exe ffprobe.exe "$GITHUB_WORKSPACE"

        # copy required runtime DLLs
        cp /mingw64/bin/libbz2-1.dll        "$GITHUB_WORKSPACE"
        cp /mingw64/bin/liblzma-5.dll       "$GITHUB_WORKSPACE"
        cp /mingw64/bin/libiconv-2.dll      "$GITHUB_WORKSPACE"
        cp /mingw64/bin/libwinpthread-1.dll "$GITHUB_WORKSPACE"
        cp /mingw64/bin/libgcc_s_seh-1.dll  "$GITHUB_WORKSPACE"
        cp /mingw64/bin/libstdc++-6.dll     "$GITHUB_WORKSPACE"

        # copy whichever OpenCL loader exists
        if [ -f /mingw64/bin/OpenCL.dll ]; then
            cp /mingw64/bin/OpenCL.dll "$GITHUB_WORKSPACE"
        elif [ -f /mingw64/bin/libOpenCL.dll ]; then
            cp /mingw64/bin/libOpenCL.dll "$GITHUB_WORKSPACE"
        fi

    # 5 – upload everything
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gopro-max-ffmpeg-windows
        path: |
          ffmpeg.exe
          ffprobe.exe
          libbz2-1.dll
          liblzma-5.dll
          libiconv-2.dll
          libwinpthread-1.dll
          libgcc_s_seh-1.dll
          libstdc++-6.dll
          OpenCL.dll?
          libOpenCL.dll?
