name: Build GoPro‑MAX FFmpeg (cal‑filter) – Windows
on:
  workflow_dispatch:

jobs:
  win64:
    runs-on: windows-latest
    steps:
    # workspace
    - uses: actions/checkout@v4

    # MSYS2 toolchain + OpenCL
    - name: MSYS2 setup
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
          git
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-yasm
          mingw-w64-x86_64-nasm
          mingw-w64-x86_64-opencl-headers
          mingw-w64-x86_64-opencl-icd

    # build static x264
    - name: Build x264 (static)
      shell: msys2 {0}
      run: |
        set -e
        git clone --depth 1 https://code.videolan.org/videolan/x264.git
        cd x264
        ./configure --enable-static --disable-opencl --prefix=/mingw64
        make -j$(nproc)
        make install

    # build FFmpeg fork – opencl‑cal branch
    - name: Build FFmpeg with gopromax_opencl_cal
      shell: msys2 {0}
      run: |
        set -e
        git clone https://github.com/gmat/goproMax-ffmpeg-v5.git
        cd goproMax-ffmpeg-v5
        git checkout opencl-cal
        ./configure \
          --cc=gcc \
          --target-os=mingw32 --arch=x86_64 \
          --enable-cross-compile \
          --enable-gpl --enable-nonfree \
          --enable-opencl \
          --enable-libx264 \
          --disable-asm --disable-doc
        make -j$(nproc)

        # binaries
        cp ffmpeg.exe ffprobe.exe "$GITHUB_WORKSPACE"

        # runtime DLLs
        for D in libbz2-1 liblzma-5 libiconv-2 libwinpthread-1 \
                 libgcc_s_seh-1 libstdc++-6 zlib1; do
            cp /mingw64/bin/$D.dll "$GITHUB_WORKSPACE"
        done
        if [ -f /mingw64/bin/OpenCL.dll ]; then
            cp /mingw64/bin/OpenCL.dll "$GITHUB_WORKSPACE"
        else
            cp /mingw64/bin/libOpenCL.dll "$GITHUB_WORKSPACE"
        fi

    # upload
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gopro-max-ffmpeg-cal-win
        path: |
          ffmpeg.exe
          ffprobe.exe
          *.dll
