name: Build GoPro‑MAX FFmpeg – Windows

on:
  workflow_dispatch:

jobs:
  win-x64:
    runs-on: windows-latest
    name: Windows‑x64 build

    steps:
    - uses: actions/checkout@v4

    # ---------- MSYS2 ----------
    - name: Install MSYS2 toolchain
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
          git
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-yasm
          mingw-w64-x86_64-nasm
          mingw-w64-x86_64-opencl-headers
          mingw-w64-x86_64-opencl-icd

    # ---------- build static x264 ----------
    - name: Build static x264
      shell: msys2 {0}
      run: |
        set -e
        git clone --depth 1 https://code.videolan.org/videolan/x264.git
        cd x264
        ./configure --enable-static --disable-opencl --prefix=/mingw64
        make -j"$(nproc)
